version: 0.0
os: linux

files:
  - source: /
    destination: ~/app/dev
permissions:
  - object: ~/app/dev
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: ./script/deploy.sh
      timeout: 60
      runas: root