version: 0.0
os: linux

files:
  - source: /
    destination: home/ec2-user/app/dev
permissions:
  - object: home/ec2-user/app/dev
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: ./script/deploy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: ./script/swagger.sh
      timeout: 30
      runas: root