name: D-doit-server

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
        
    - name: Zip Build file
      run: mkdir ./build/zip && cp -r ./script ./appspec.yml ./build/libs && cd build/libs && zip -qq -r ../zip/deploy.zip .

    - name: AWS CONFIG
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  ap-northeast-2

    - name: Branch-based environment variables that rock
      uses: iamtheyammer/branch-env-vars@v1.1.3
      with:
        bevOverwrite: true
        FILE_DIR: |
          master:prod
          dev:dev

    - name: echo variables
      run: echo ${{env.FILE_DIR}}


    - name: openAPI3.yaml S3 이동
      run: aws s3 sync ./build/api-spec/ s3://d-doit-deploy/dev/

    - name: S3 Sync
      run: |
          aws s3 sync \
          --acl private \
          ./build/zip/ s3://d-doit-deploy/dev 
    
    - name: code Deploy
      run: |
        aws deploy create-deployment --application-name d-doit-deploy \
        --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name d-doit-deploy-dev \
        --s3-location bucket=${{secrets.AWS_S3_BUCKET}},bundleType=zip,key=dev/deploy.zip